branches:
  only:
    - master
before_install:
  - sudo apt-get install -qq libcunit1 libcunit1-dev
  - sudo pip install cpp-coveralls --use-mirrors
language: c
compiler:
  - gcc
  - clang
before_script:
  - mkdir build
  - cd build
  - cmake ../ -DCMAKE_BUILD_TYPE=Debug
script:
  - make
after_script:
  - make test
